import { IPL } from './ipl';

export const TEAMS: IPL[] = [
  {
    id: 1,
    name: 'Chennai Super Kings',
    website: ' www.chennaisuperkings.com',
    number: 798984645,
    image: '../../assets/csk.png',
    bestplayer: '',
  },
  {
    id: 2,
    name: 'Mumbai Indians',
    website: ' www.mumbaiindians.com',
    number: 742135932,
    image: '../../assets/MI.png',
    bestplayer: '',
  },
  {
    id: 3,
    name: 'Rajasthan Royals',
    website: 'www.rajasthanroyals.com',
    number: 954789624,
    image: '../../assets/RR.png',
    bestplayer: '',
  },
  {
    id: 4,
    name: 'Delhi Capitals',
    website: 'www.delhicapitals.com',
    number: 785 - 541234 - 825,
    image: '../../assets/Delhi.png',
    bestplayer: '',
  },
  {
    id: 5,
    name: 'Royal Challangers Banglore',
    website: 'www.royalchallengers.com',
    number: 9221812229,
    image: '../../assets/RCB.png',
    bestplayer: '',
  },
  {
    id: 6,
    name: 'Kolkata Knight Riders',
    website: 'wwwkkr.in',
    number: 92721126697,
    image: '../../assets/KKR.png',
    bestplayer: '',
  },
  {
    id: 7,
    name: 'Sunrisers Hyderabad',
    website: 'www.sunrisershyderabad.in',
    number: 7413654486,
    image: '../../assets/SRH.png',
    bestplayer: '',
  },
  {
    id: 8,
    name: 'Gujarat Lions',
    website: 'www.gujaratlions.com',
    number: 7856564789,
    image: '../../assets/Gujarat_Lions.png',
    bestplayer: '',
  },
  {
    id: 9,
    name: 'Kings XI Punjab',
    website: 'www.kixp.in',
    number: 8412235529,
    image: '../../assets/KXI.png',
    bestplayer: '',
  },
  {
    id: 10,
    name: 'Rising Pune SuperGaints',
    website: 'www.rps.in',
    number: 748569889,
    image: '../../assets/RPS.png',
    bestplayer: '',
  },
];
